### ISSUE TITLE
Don't allow`_` in bundleidentifier 

### ISSUE THREAD

**Issue by passsy** [phntmxyz/ios_publishing_sidekick_plugin#3]
The error of Xcode is not great, we can do better.

Check that `bundleIdentifier` doesn't contain underscores

<img width="565" alt="Screen-Shot-2023-02-01-15-32-44 10" src="https://user-images.githubusercontent.com/1096485/216071727-ede50798-16bc-417f-b8d2-c87df8b3ba7f.png">

https://stackoverflow.com/questions/71981688/the-attribute-name-is-invalid-xcode-flutter-app-archiving

**Comment by jxstxn1** [comment]
Fixed by #5
